"""GPI Document Hub - Shared Document Type Constants

Extracted from server.py. Shared across routers and services.
"""


class TransactionAction:
    """Track what action was taken on the BC side"""
    NONE = "NONE"                       # No BC action taken
    VALIDATED = "VALIDATED"             # Square9: Validation passed, stored in SharePoint
    LINKED_ONLY = "LINKED_ONLY"         # Document attached to existing record
    DRAFT_CREATED = "DRAFT_CREATED"     # Draft invoice header created
    DRAFT_WITH_LINES = "DRAFT_WITH_LINES"  # Future: draft with lines

# Phase 4: CREATE_DRAFT_HEADER configuration
# These are safety thresholds that must be met before creating a draft
DRAFT_CREATION_CONFIG = {
    # Match methods eligible for draft creation (high confidence methods only)
    "eligible_match_methods": ["exact_no", "exact_name", "normalized", "alias"],
    # Minimum match score for draft creation (stricter than auto-link)
    "min_match_score_for_draft": 0.92,
    # Minimum AI confidence for draft creation
    "min_confidence_for_draft": 0.92,
    # Number of days to look back for duplicate check
    "duplicate_lookback_days": 365,
}

# Default Job Type configurations - Production Grade
DEFAULT_JOB_TYPES = {
    # ==================== AP DOCUMENTS (Category: AP) ====================
    "AP_Invoice": {
        "job_type": "AP_Invoice",
        "display_name": "AP Invoice (Vendor Invoice)",
        "category": "AP",
        "automation_level": 1,
        "min_confidence_to_auto_link": 0.85,
        "min_confidence_to_auto_create_draft": 0.95,
        "po_validation_mode": "PO_IF_PRESENT",
        "allow_duplicate_check_override": False,
        "requires_human_review_if_exception": True,
        "vendor_match_threshold": 0.80,
        "vendor_match_strategies": ["alias", "exact_no", "exact_name", "normalized", "fuzzy"],
        "sharepoint_folder": "AP_Invoices",
        "bc_entity": "purchaseInvoices",
        "required_extractions": ["vendor", "invoice_number", "amount"],
        "optional_extractions": ["po_number", "due_date", "line_items"],
        "enabled": True
    },
    "Sales_PO": {
        "job_type": "Sales_PO",
        "display_name": "Sales PO (Customer Purchase Order)",
        "category": "AP",
        "automation_level": 1,
        "min_confidence_to_auto_link": 0.80,
        "min_confidence_to_auto_create_draft": 0.92,
        "po_validation_mode": "PO_NOT_REQUIRED",
        "allow_duplicate_check_override": False,
        "requires_human_review_if_exception": True,
        "vendor_match_threshold": 0.80,
        "vendor_match_strategies": ["exact_no", "exact_name", "normalized", "fuzzy"],
        "sharepoint_folder": "Sales_POs",
        "bc_entity": "salesOrders",
        "required_extractions": ["customer", "po_number", "order_date"],
        "optional_extractions": ["amount", "ship_to", "line_items"],
        "enabled": True
    },
    "AR_Invoice": {
        "job_type": "AR_Invoice",
        "display_name": "AR Invoice (Outgoing Invoice)",
        "category": "AP",
        "automation_level": 0,
        "min_confidence_to_auto_link": 0.90,
        "min_confidence_to_auto_create_draft": 0.98,
        "po_validation_mode": "PO_NOT_REQUIRED",
        "allow_duplicate_check_override": False,
        "requires_human_review_if_exception": True,
        "vendor_match_threshold": 0.80,
        "vendor_match_strategies": ["exact_no", "exact_name", "normalized", "fuzzy"],
        "sharepoint_folder": "AR_Invoices",
        "bc_entity": "salesInvoices",
        "required_extractions": ["customer", "invoice_number", "amount"],
        "optional_extractions": ["due_date", "line_items"],
        "enabled": True
    },
    "Credit_Memo": {
        "job_type": "Credit_Memo",
        "display_name": "Credit Memo",
        "category": "Finance",
        "automation_level": 2,
        "min_confidence_to_auto_link": 0.85,
        "min_confidence_to_auto_create_draft": 0.95,
        "po_validation_mode": "OPTIONAL",
        "allow_duplicate_check_override": False,
        "requires_human_review_if_exception": True,
        "vendor_match_threshold": 0.75,
        "vendor_match_strategies": ["alias", "exact_no", "exact_name", "normalized", "fuzzy"],
        "sharepoint_folder": "Credit_Memos",
        "bc_entity": "purchaseCreditMemos",
        "required_extractions": ["vendor", "amount"],
        "optional_extractions": ["credit_memo_number", "original_invoice_reference", "reason", "date"],
        "keywords": ["credit memo", "credit invoice", "credit note", "refund", "adjustment", "debit memo"],
        "enabled": True
    },
    "Remittance": {
        "job_type": "Remittance",
        "display_name": "Remittance Advice (Payment Confirmation)",
        "category": "AP",
        "automation_level": 1,
        "min_confidence_to_auto_link": 0.75,
        "min_confidence_to_auto_create_draft": 0.95,
        "po_validation_mode": "PO_NOT_REQUIRED",
        "allow_duplicate_check_override": True,
        "requires_human_review_if_exception": True,
        "vendor_match_threshold": 0.75,
        "vendor_match_strategies": ["exact_no", "exact_name", "normalized", "fuzzy"],
        "sharepoint_folder": "Remittances",
        "bc_entity": "vendorPayments",
        "required_extractions": ["vendor", "payment_amount", "payment_date"],
        "optional_extractions": ["invoice_references", "check_number"],
        "enabled": True
    },
    "Freight_Document": {
        "job_type": "Freight_Document",
        "display_name": "Freight Document (BOL/HAWB/Shipping)",
        "category": "AP",
        "automation_level": 1,
        "min_confidence_to_auto_link": 0.80,
        "min_confidence_to_auto_create_draft": 0.92,
        "po_validation_mode": "PO_IF_PRESENT",
        "allow_duplicate_check_override": False,
        "requires_human_review_if_exception": True,
        "vendor_match_threshold": 0.75,
        "vendor_match_strategies": ["exact_no", "exact_name", "normalized", "fuzzy"],
        "sharepoint_folder": "Freight",
        "bc_entity": "purchaseReceipts",
        "required_extractions": ["shipper", "tracking_number"],
        "optional_extractions": ["consignee", "ship_date", "weight", "pieces", "origin", "destination", "carrier"],
        "enabled": True
    },
    "Warehouse_Document": {
        "job_type": "Warehouse_Document",
        "display_name": "Warehouse Document (Receipt/Shipment)",
        "category": "AP",
        "automation_level": 1,
        "min_confidence_to_auto_link": 0.80,
        "min_confidence_to_auto_create_draft": 0.92,
        "po_validation_mode": "PO_IF_PRESENT",
        "allow_duplicate_check_override": False,
        "requires_human_review_if_exception": True,
        "vendor_match_threshold": 0.75,
        "vendor_match_strategies": ["alias", "exact_no", "exact_name", "normalized", "fuzzy"],
        "sharepoint_folder": "Warehouse",
        "bc_entity": "warehouseReceipts",
        "required_extractions": ["document_number", "location"],
        "optional_extractions": ["item_numbers", "quantities", "bin_codes", "receipt_date"],
        "enabled": True
    },
    "Purchase_Order": {
        "job_type": "Purchase_Order",
        "display_name": "Purchase Order (Outgoing PO to Vendor)",
        "category": "AP",
        "automation_level": 1,
        "min_confidence_to_auto_link": 0.85,
        "min_confidence_to_auto_create_draft": 0.92,
        "po_validation_mode": "PO_NOT_REQUIRED",
        "allow_duplicate_check_override": False,
        "requires_human_review_if_exception": True,
        "vendor_match_threshold": 0.80,
        "vendor_match_strategies": ["alias", "exact_no", "exact_name", "normalized", "fuzzy"],
        "sharepoint_folder": "Purchase_Orders",
        "bc_entity": "purchaseOrders",
        "required_extractions": ["vendor", "po_number"],
        "optional_extractions": ["amount", "order_date", "ship_to", "line_items"],
        "keywords": ["purchase order", "po", "order", "vendor", "supplier"],
        "enabled": True
    },
    
    # ==================== SALES DOCUMENTS (Category: Sales) ====================
    "Sales_Order": {
        "job_type": "Sales_Order",
        "display_name": "Sales Order (Customer PO)",
        "category": "Sales",
        "automation_level": 0,
        "min_confidence_to_auto_link": 0.80,
        "min_confidence_to_auto_create_draft": 0.90,
        "po_validation_mode": "PO_NOT_REQUIRED",
        "allow_duplicate_check_override": False,
        "requires_human_review_if_exception": True,
        "vendor_match_threshold": 0.80,
        "vendor_match_strategies": ["exact_no", "exact_name", "normalized", "fuzzy"],
        "sharepoint_folder": "Sales_Orders",
        "bc_entity": "salesOrders",
        "required_extractions": ["customer", "po_number"],
        "optional_extractions": ["amount", "ship_to", "line_items", "order_date"],
        "keywords": ["purchase order", "po", "order", "buy", "quantity", "ship to", "bill to"],
        "enabled": True
    },
    "DS_Sales_Order": {
        "job_type": "DS_Sales_Order",
        "display_name": "Drop-Ship Sales Order",
        "category": "Sales",
        "automation_level": 0,
        "min_confidence_to_auto_link": 0.80,
        "min_confidence_to_auto_create_draft": 0.90,
        "po_validation_mode": "PO_NOT_REQUIRED",
        "allow_duplicate_check_override": False,
        "requires_human_review_if_exception": True,
        "vendor_match_threshold": 0.80,
        "vendor_match_strategies": ["exact_no", "exact_name", "normalized", "fuzzy"],
        "sharepoint_folder": "Sales_Orders/Drop_Ship",
        "bc_entity": "salesOrders",
        "required_extractions": ["customer", "po_number"],
        "optional_extractions": ["amount", "ship_to", "line_items", "order_date"],
        "keywords": ["drop ship", "direct ship", "ship direct", "drop-ship", "purchase order"],
        "enabled": True
    },
    "WH_Sales_Order": {
        "job_type": "WH_Sales_Order",
        "display_name": "Warehouse Sales Order",
        "category": "Sales",
        "automation_level": 0,
        "min_confidence_to_auto_link": 0.80,
        "min_confidence_to_auto_create_draft": 0.90,
        "po_validation_mode": "PO_NOT_REQUIRED",
        "allow_duplicate_check_override": False,
        "requires_human_review_if_exception": True,
        "vendor_match_threshold": 0.80,
        "vendor_match_strategies": ["exact_no", "exact_name", "normalized", "fuzzy"],
        "sharepoint_folder": "Sales_Orders/Warehouse",
        "bc_entity": "salesOrders",
        "required_extractions": ["customer", "po_number"],
        "optional_extractions": ["amount", "ship_to", "line_items", "order_date", "location_code"],
        "keywords": ["purchase order", "warehouse", "stock", "wh", "location"],
        "enabled": True
    },
    "Sales_Quote": {
        "job_type": "Sales_Quote",
        "display_name": "Sales Quote (Proposal)",
        "category": "Sales",
        "automation_level": 0,
        "min_confidence_to_auto_link": 0.70,
        "min_confidence_to_auto_create_draft": 0.90,
        "po_validation_mode": "PO_NOT_REQUIRED",
        "allow_duplicate_check_override": True,
        "requires_human_review_if_exception": True,
        "vendor_match_threshold": 0.70,
        "vendor_match_strategies": ["exact_name", "normalized"],
        "sharepoint_folder": "Sales_Quotes",
        "bc_entity": "salesQuotes",
        "required_extractions": ["customer"],
        "optional_extractions": ["amount", "valid_until"],
        "keywords": ["quote", "quotation", "proposal", "estimate", "pricing", "valid until"],
        "enabled": True
    },
    "Order_Confirmation": {
        "job_type": "Order_Confirmation",
        "display_name": "Order Confirmation",
        "category": "Sales",
        "automation_level": 0,
        "min_confidence_to_auto_link": 0.70,
        "min_confidence_to_auto_create_draft": 0.90,
        "po_validation_mode": "PO_NOT_REQUIRED",
        "allow_duplicate_check_override": True,
        "requires_human_review_if_exception": True,
        "vendor_match_threshold": 0.70,
        "vendor_match_strategies": ["exact_name", "normalized"],
        "sharepoint_folder": "Sales_Confirmations",
        "bc_entity": "salesOrders",
        "required_extractions": ["order_number"],
        "optional_extractions": ["customer", "amount"],
        "keywords": ["confirmation", "confirmed", "order acknowledgment", "acknowledge"],
        "enabled": True
    },
    "Inventory_Report": {
        "job_type": "Inventory_Report",
        "display_name": "Inventory Report",
        "category": "Sales",
        "automation_level": 0,
        "min_confidence_to_auto_link": 0.60,
        "min_confidence_to_auto_create_draft": 0.90,
        "po_validation_mode": "PO_NOT_REQUIRED",
        "allow_duplicate_check_override": True,
        "requires_human_review_if_exception": False,
        "vendor_match_threshold": 0.60,
        "vendor_match_strategies": ["normalized"],
        "sharepoint_folder": "Inventory_Reports",
        "bc_entity": "items",
        "required_extractions": [],
        "optional_extractions": ["warehouse", "item_numbers", "quantities"],
        "keywords": ["inventory", "stock", "on hand", "available", "warehouse"],
        "enabled": True
    },
    "Shipping_Document": {
        "job_type": "Shipping_Document",
        "display_name": "Shipping Document (BOL/Shipment)",
        "category": "Warehouse",
        "automation_level": 1,
        "min_confidence_to_auto_link": 0.70,
        "min_confidence_to_auto_create_draft": 0.90,
        "po_validation_mode": "PO_IF_PRESENT",
        "allow_duplicate_check_override": True,
        "requires_human_review_if_exception": True,
        "vendor_match_threshold": 0.70,
        "vendor_match_strategies": ["exact_name", "normalized"],
        "sharepoint_folder": "Shipping_Docs",
        "bc_entity": "salesShipments",
        "required_extractions": ["bol_number", "ship_date"],
        "optional_extractions": ["po_number", "tracking_number", "shipper", "consignee", "carrier", "weight", "pieces", "pro_number"],
        "keywords": ["ship", "shipping", "delivery", "dispatch", "release", "pick up", "bill of lading", "bol", "tracking", "straight bill", "packing list", "packing slip", "pack list", "pick list", "pick qty"],
        "enabled": True
    },
    "Quality_Issue": {
        "job_type": "Quality_Issue",
        "display_name": "Quality Issue / Complaint",
        "category": "Sales",
        "automation_level": 0,
        "min_confidence_to_auto_link": 0.60,
        "min_confidence_to_auto_create_draft": 0.90,
        "po_validation_mode": "PO_NOT_REQUIRED",
        "allow_duplicate_check_override": True,
        "requires_human_review_if_exception": True,
        "vendor_match_threshold": 0.60,
        "vendor_match_strategies": ["normalized"],
        "sharepoint_folder": "Quality_Issues",
        "bc_entity": "items",
        "required_extractions": [],
        "optional_extractions": ["customer", "item", "description"],
        "keywords": ["quality", "defect", "damage", "complaint", "issue", "problem", "ncr", "claim"],
        "enabled": True
    },
    "Return_Request": {
        "job_type": "Return_Request",
        "display_name": "Return Request / RMA",
        "category": "Sales",
        "automation_level": 0,
        "min_confidence_to_auto_link": 0.70,
        "min_confidence_to_auto_create_draft": 0.90,
        "po_validation_mode": "PO_NOT_REQUIRED",
        "allow_duplicate_check_override": True,
        "requires_human_review_if_exception": True,
        "vendor_match_threshold": 0.70,
        "vendor_match_strategies": ["exact_name", "normalized"],
        "sharepoint_folder": "Returns",
        "bc_entity": "salesCreditMemos",
        "required_extractions": [],
        "optional_extractions": ["customer", "amount", "reason"],
        "keywords": ["return", "rma", "credit", "refund", "send back"],
        "enabled": True
    },
    "Warehouse_Receipt": {
        "job_type": "Warehouse_Receipt",
        "display_name": "Warehouse Receipt",
        "category": "Warehouse",
        "automation_level": 1,
        "min_confidence_to_auto_link": 0.80,
        "min_confidence_to_auto_create_draft": 0.92,
        "po_validation_mode": "PO_IF_PRESENT",
        "allow_duplicate_check_override": False,
        "requires_human_review_if_exception": True,
        "vendor_match_threshold": 0.75,
        "vendor_match_strategies": ["alias", "exact_no", "exact_name", "normalized", "fuzzy"],
        "sharepoint_folder": "Warehouse_Receipts",
        "bc_entity": "warehouseReceipts",
        "required_extractions": ["receipt_number"],
        "optional_extractions": ["customer", "location", "item_numbers", "quantities", "receipt_date"],
        "keywords": ["warehouse receipt", "non-negotiable", "goods received", "stored in warehouse"],
        "enabled": True
    },
    "Unknown_Document": {
        "job_type": "Unknown_Document",
        "display_name": "Unknown / Unclassified",
        "category": "Unknown",
        "automation_level": 0,
        "min_confidence_to_auto_link": 0.50,
        "min_confidence_to_auto_create_draft": 0.95,
        "po_validation_mode": "PO_NOT_REQUIRED",
        "allow_duplicate_check_override": True,
        "requires_human_review_if_exception": True,
        "vendor_match_threshold": 0.50,
        "vendor_match_strategies": ["normalized"],
        "sharepoint_folder": "Unclassified",
        "bc_entity": "documents",
        "required_extractions": [],
        "optional_extractions": [],
        "keywords": [],
        "enabled": True
    }
}

# Vendor Alias Map (company-specific)
