export const APP_VERSION = "2.4.0";

export const CHANGELOG = [
  {
    version: "2.4.0",
    date: "2026-04-18",
    title: "Cold-Start Peer Matching — Bootstrap New Customers Instantly",
    changes: [
      { type: "feature", text: "TF-IDF customer fingerprints — every customer with learned patterns gets a token vector (item_no + description), cached in intake_customer_fingerprints with 24h TTL" },
      { type: "feature", text: "Cold-start lookup — when a new/empty customer has an inbound PO, we cosine-match their line items against all known fingerprints and surface top-3 similar customers with matched-token receipts" },
      { type: "feature", text: "Inherited suggestions — the top peer's most-frequent non-retired lines appear as reviewable suggestions labelled with source customer + similarity %" },
      { type: "feature", text: "Promote-to-own — reviewer clicks the up-arrow and that inherited line becomes the target customer's first real learned pattern (audit event: inherited_suggestion_promoted)" },
      { type: "feature", text: "Fingerprint auto-invalidation — every feedback event (accept/reject/retire/promote) invalidates the affected fingerprint so cold-start matches stay fresh" },
      { type: "feature", text: "3 new /api/intake/* endpoints: promote-inherited, rebuild-fingerprints, similar-customers (diagnostic)" },
      { type: "improvement", text: "Pure Python TF-IDF with numpy/Counter — no sklearn dep, no API calls, no embedding cost; deterministic + transparent (reviewers see which tokens matched)" },
    ],
  },
  {
    version: "2.3.0",
    date: "2026-04-18",
    title: "Learning Feedback Loop — Every Click Is Training Data",
    changes: [
      { type: "feature", text: "Inline thumbs-up/thumbs-down on every suggested line, bounds violation, and unmatched item in the IntakeLearningPanel — captured as structured events in a new `intake_learning_events` collection" },
      { type: "feature", text: "Pattern confidence auto-adapts: accepts bump occurrences/frequency, rejects decay them, accept rate <40% over ≥5 samples → pattern retired, ≥90% → pattern marked trusted" },
      { type: "feature", text: "Bounds-violation overrides widen the pattern's ±2σ envelope by 10% per override; confirms keep the sample as an outlier" },
      { type: "feature", text: "New Pattern Health panel on /intake/learning — Trusted / Drifting / Retired / Unscored counters, per-customer drill-down, recent reviewer-feedback feed" },
      { type: "feature", text: "Nightly Pattern Hygiene scheduler retires stale patterns automatically; manual 'Pattern hygiene' button on dashboard" },
      { type: "feature", text: "Unmatched items can be confirmed-new (queued for BC admin) or mapped-to-existing (alias saved for auto-match next time)" },
      { type: "feature", text: "4 new /api/intake/* endpoints: insights/feedback, learning/pattern-health, learning/hygiene, learning/events" },
    ],
  },
  {
    version: "2.2.1",
    date: "2026-04-18",
    title: "De-pilotization & Doc-Level Intelligence Panel",
    changes: [
      { type: "improvement", text: "De-pilotized UI framing — 'Inside Sales Pilot' tab renamed to 'Sales Intake', 'Pilot Docs' → 'Intake Docs', banner + stat labels neutralized. The pilot is now part of the overall hub." },
      { type: "feature", text: "IntakeLearningPanel now appears on every Document Detail page — Nikki sees '±2σ qty flag', 'Energy Surcharge suggested', 'item not in BC catalog' the moment she opens any Giovanni PO, no drawer-digging required." },
    ],
  },
  {
    version: "2.2.0",
    date: "2026-04-18",
    title: "Intake Learning — Hub-Wide Giovanni Pattern",
    changes: [
      { type: "feature", text: "Intake Learning orchestrator — every ingested PO, sales order, invoice, and inventory XLS now gets Giovanni-style BC + Spiro cross-reference (customer match, Spiro ISR, learned pattern count, recurring-line suggestions, ±2σ qty bounds, BC item-catalog match)" },
      { type: "feature", text: "New /intake/learning dashboard — hub-wide KPIs, top customers by learning coverage, flagged-for-review list, backfill controls" },
      { type: "feature", text: "IntakeLearningPanel surfaced on every Document Detail page + XLS staging drawer — cold-start transparency: 'no BC learning yet' is always explicit" },
      { type: "feature", text: "Daily auto-refresh scheduler — re-learns customers with new BC posted-order activity (24h window, configurable)" },
      { type: "feature", text: "BC write-back hook — moment a sales order is posted to BC, that customer's patterns are re-learned in-process so the next ingest picks them up instantly" },
      { type: "feature", text: "7 new /api/intake/* endpoints: summary, backfill, refresh-active, run, run-xls, insights, insights-xls, flagged" },
      { type: "improvement", text: "SALES_INVOICE (GPI ZD00010, blanket sales orders) now correctly included in learning scope" },
      { type: "improvement", text: "Never writes to BC — pure learning + visibility layer, safety guards preserved" },
    ],
  },
  {
    version: "2.1.0",
    date: "2026-04-14",
    title: "Inside Sales Pilot — Controlled Ingestion",
    changes: [
      { type: "feature", text: "Inside Sales Pilot — ingest-only polling for mkoch & nhannover mailboxes with 5-layer BC write safety" },
      { type: "feature", text: "Relevance filtering — keyword + filename matching, noise rejection (certificates, dunnage, signatures)" },
      { type: "feature", text: "Structured sales extraction — customer, PO, order number, ship-to, items, quantities with quality scoring" },
      { type: "feature", text: "BC Production cross-validation — read-only customer match, order lookup, item validation, amount range check" },
      { type: "feature", text: "Pilot dashboard — /api/inside-sales-pilot/status, documents, runs, logs, extraction-review, validation-results" },
      { type: "improvement", text: "Smart PO extraction — rejects garbage (rate, intment, number.) while catching real patterns (W117579, WR112624)" },
    ],
  },
  {
    version: "2.0.0",
    date: "2026-04-14",
    title: "Unified Governance & AP Advisory Phase 3",
    changes: [
      { type: "feature", text: "Governance Dashboard — cross-pipeline view of SO + AP learning, drift controls, and system health" },
      { type: "feature", text: "AP Invoice Advisory Phase 3 — suggestion approve/reject/apply workflow, impact review, drift controls, vendor hotspots" },
      { type: "fix", text: "Draft PI Preview was showing identical amounts on all lines — now distributes proportionally using template usage rates" },
    ],
  },
  {
    version: "1.12.0",
    date: "2026-04-13",
    title: "AP Advisory Phases 1-2 & Status Model Cleanup",
    changes: [
      { type: "feature", text: "AP Invoice Vendor Advisory — reviewer, explainer, feedback, diagnostics, calibration, learning suggestions" },
      { type: "feature", text: "Maturity Checkpoint & Reusability Review — system-wide readiness assessment for framework reuse" },
      { type: "fix", text: "Status model cleanup — fixed validation state overrides, reprocess loop, and completed-doc downgrade bug" },
      { type: "fix", text: "Readiness extraction quality gate — docs with 0% extraction no longer auto-clear" },
    ],
  },
  {
    version: "1.11.0",
    date: "2026-04-13",
    title: "Governed Learning Pipeline Complete",
    changes: [
      { type: "feature", text: "Feedback-to-Learning Pipeline — converts reviewer feedback into candidate profile suggestions" },
      { type: "feature", text: "Learning Suggestion Approval Workflow — governed approve/reject/apply with full audit trail" },
      { type: "feature", text: "Learning Apply-Impact Review — pre/post apply outcome comparison" },
      { type: "feature", text: "Profile Drift Controls — change cadence monitoring, risk classification" },
      { type: "feature", text: "Rep Overrides Management UI — admin CRUD for business exceptions" },
      { type: "feature", text: "Customer Hotspot Review — cross-signal friction analysis with root-cause diagnosis" },
    ],
  },
  {
    version: "1.10.0",
    date: "2026-04-13",
    title: "SO Advisory Tuning & Calibration",
    changes: [
      { type: "feature", text: "Confidence Calibration — heuristic penalty system preserving raw values" },
      { type: "feature", text: "Ship-To & Item/UOM Sensitivity Tuning — pre-LLM analysis with context-aware severity" },
      { type: "feature", text: "Explanation Wording Refinement — evidence-calibrated tone system (6 categories)" },
      { type: "feature", text: "Strong-Profile Behavior Tuning — reduced false positives for mature customers" },
      { type: "feature", text: "Post-Tuning Calibration Review — comprehensive impact analysis" },
    ],
  },
  {
    version: "1.9.0",
    date: "2026-04-13",
    title: "Sales Order Governed Learning Foundation",
    changes: [
      { type: "feature", text: "Customer Posting Profiles — BC backfill + incremental learning from posted orders" },
      { type: "feature", text: "SO Readiness Reviewer — LLM-assisted advisory (never changes posting decisions)" },
      { type: "feature", text: "SO Decision Explainer — plain-English explanations of advisory results" },
      { type: "feature", text: "Reviewer Feedback Capture & Analytics — structured human corrections" },
      { type: "feature", text: "Unified SO Advisory Panel — consolidated explainer + review + profile + feedback" },
      { type: "feature", text: "Disagreement Diagnostics — root-cause classification of reviewer disagreements" },
    ],
  },
  {
    version: "1.8.0",
    date: "2026-04-12",
    title: "LLM Abstraction & Daily Trace System",
    changes: [
      { type: "feature", text: "LLM Provider Abstraction — Emergent + Ollama providers with env-based routing" },
      { type: "feature", text: "Decision Explainer Service — plain-English document workflow explanations" },
      { type: "feature", text: "Side-by-Side Extraction Comparison — baseline vs candidate provider testing" },
      { type: "feature", text: "Vendor Resolution Ranking Assist — LLM-assisted disambiguation for uncertain matches" },
      { type: "feature", text: "Daily Random Trace System — 15 random PROD PI comparisons with trend tracking" },
      { type: "feature", text: "Template Value Injection — merges template structure with live extracted values" },
    ],
  },
  {
    version: "1.7.0",
    date: "2026-04-11",
    title: "Validation Gap Auto-Fixer & Freight Rules Engine",
    changes: [
      { type: "feature", text: "Gap Closer 8 (PO Learning) & Gap Closer 9 (Vendor Auto-Resolution) — closed 45 blocking gaps" },
      { type: "feature", text: "Run Full Cycle expanded to 10 steps with one-button orchestration" },
      { type: "feature", text: "Freight Business Rules Engine — controller rules codified (order patterns, location routing, carrier detection)" },
      { type: "feature", text: "Freight-specific readiness checks and enhanced duplicate detection" },
      { type: "fix", text: "Vendor alias duplicate key error resolved (UUID-based alias_id)" },
      { type: "fix", text: "Escalation death spiral — auto_escalation demoted from blocking to advisory" },
      { type: "fix", text: "Noise learning events cleanup — self-corrections no longer pollute dashboard" },
    ],
  },
  {
    version: "1.6.0",
    date: "2026-03-21",
    title: "Intake Benchmark: GPI Hub vs Square 9",
    changes: [
      { type: "feature", text: "Intake Benchmark workspace for side-by-side document processing comparison" },
      { type: "feature", text: "Run management: create, complete, archive benchmark runs" },
      { type: "feature", text: "Per-document scoring with truth values, GPI auto-population, and Square 9 manual entry" },
      { type: "feature", text: "Auto-scoring with normalization (case-insensitive, PO prefix removal, amount tolerance)" },
      { type: "feature", text: "Results dashboard with KPI comparison, breakdowns, and key insights" },
      { type: "feature", text: "Excel export with Documents + Summary sheets" },
      { type: "feature", text: "CSV import for bulk document seeding" },
    ],
  },
  {
    version: "1.5.0",
    date: "2026-03-21",
    title: "Frontend Consolidation & Platform Hardening",
    changes: [
      { type: "feature", text: "Unified Queue Page with workflow category filters (AP, Sales, Operations) and date range picker" },
      { type: "feature", text: "Vendor Intelligence & Stable Vendors moved into Settings hub" },
      { type: "improvement", text: "Navigation consolidated from 8 to 7 items for cleaner UX" },
      { type: "feature", text: "App versioning system with changelog" },
    ],
  },
  {
    version: "1.4.0",
    date: "2026-03-20",
    title: "BC Shipments, Rep Assignment & Server Extraction",
    changes: [
      { type: "feature", text: "BC Sales Order shipment events synced into Inventory Ledger as outbound movements" },
      { type: "feature", text: "Customer & salesperson sync from Business Central with rep assignment service" },
      { type: "improvement", text: "Extracted 600+ lines from server.py into dedicated domain services" },
    ],
  },
  {
    version: "1.0.0",
    date: "2026-03-16",
    title: "Initial Release",
    changes: [
      { type: "feature", text: "Document classification and workflow pipeline" },
      { type: "feature", text: "PO extraction from multiple document fields" },
      { type: "feature", text: "Business Central and SharePoint integration" },
      { type: "feature", text: "Vendor matching with multi-source intelligence" },
    ],
  },
];
